import Head from "next/head";
import { Header } from "../components";

const cart = () => {
  return (
    <>
      <Head>
        <title>Cart - Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
      </main>
    </>
  );
};

export default cart;
