import Head from "next/head";
import Image from "next/legacy/image";
import { useEffect, useState } from "react";
import { CartCard, Header } from "../components";

const cart = () => {
  const [products, setProducts] = useState(null);

  useEffect(() => {
    const fetchProducts = async () => {
      const response = await fetch("https://dummyjson.com/products");
      const responseJson = await response.json();
      setProducts(responseJson);
    };
    fetchProducts();
  }, []);

  console.log("products", products);

  return (
    <>
      <Head>
        <title>Cart - Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="flex flex-col md:flex-row mx-2 sm:px-4 md:mx-10 lg:mx-16 py-4 bg-[#f9f7f7] min-h-[calc(100vh-130px)]">
          <div className="flex-grow">
            <div className="w-full bg-red-300 relative h-[380px] rounded-lg">
              <Image
                src="/img/cartAd.jpg"
                alt="cartAd"
                layout="fill"
                className="rounded-lg"
              />
            </div>
            <div>
              <h1 className="mt-3 mb-2 font-bold text-lg">Your Amazon Cart</h1>
              <div>
                {products?.products?.slice(0, 4)?.map((product, index) => (
                  <CartCard key={index} product={product} />
                ))}
              </div>
            </div>
          </div>
          <div className="md:w-[250px] lg:w-[300px]"></div>
        </div>
      </main>
    </>
  );
};

export default cart;
