import axios from "axios";
import Head from "next/head";
import { Header, Banner, Products, Feeds } from "../components";

export default function Home({ products, movies, books }) {
  return (
    <>
      <Head>
        <title>Home - Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Header */}
        <Header />

        <section>
          {/* Banner */}
          <Banner />

          {/* Product Feeds */}
          <Feeds products={products} movies={movies} books={books} />
        </section>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  let [products, books, movies] = await Promise.all([
    axios.get("https://dummyjson.com/products?limit=100"),
    axios.get("https://api.itbook.store/1.0/new"),
    axios.get(
      `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.NEXT_PUBLIC_MOVIE_APIKEY}&language=en-US`
    ),
  ]);
  return {
    props: {
      products: products.data.products,
      books: books.data.books,
      movies: movies.data.results,
    },
  };
};
