import axios from "axios";
import Head from "next/head";
import { Header, Banner, Products } from "../components";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Home - Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Header */}
        <Header />

        <section className="">
          {/* Banner */}
          <Banner />

          {/* Top Products */}
          <Products products={products} index={[0, 8]} />
        </section>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  let { data } = await axios.get("https://dummyjson.com/products?limit=100");
  return {
    props: {
      products: data.products,
    },
  };
};
